version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    container_name: bot
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data:
